### ISSUE TITLE
1、JPA多对多映射关系出现死循环导致内存泄露报错 答：找了大半天的问题，按照@ManyToMany源码示例配置仍然错误，最后去掉lombok的@Data注解解决问题，使用原始setter，getter。暂不知道原因？？？

### ISSUE THREAD

**Issue by King-Pan** [ScnuWang/SpringBoot#1]
1、JPA多对多映射关系出现死循环导致内存泄露报错
答：找了大半天的问题，按照@ManyToMany源码示例配置仍然错误，最后去掉lombok的@Data注解解决问题，使用原始setter，getter。暂不知道原因？？？

我之前遇到过，是因为toString方法互相引用，导致内存泄漏，手写toString方法，一方引用就行

**Comment by ScnuWang** [comment]
多谢解答！
